#!/usr/bin/env python3
"""PC side of the audio export (rewrite): open COM11 with clean reset like the
diagnostic script, send 'GO', parse the hex dump, emit src/hug_tts_audio.h.

Run: C:\\Users\\14058\\.platformio\\penv\\Scripts\\python.exe scripts\\capture_hug_audio.py
"""
import re
import sys
import time
from pathlib import Path

import serial

ROOT = Path(__file__).resolve().parents[1]
OUT_H = ROOT / "src" / "hug_tts_audio.h"
PORT = "COM11"
SENTENCE_COUNT = 8


def emit(pcms: dict[int, bytes]) -> None:
    lines = [
        "// Auto-generated by scripts/capture_hug_audio.py — do not edit by hand.",
        "// Pre-synthesized hug comfort lines (PCM16 mono 16 kHz), indexes match",
        "// HUG_COMFORT_LINES in src/config.h. Played synchronously with the text.",
        "#ifndef HUG_TTS_AUDIO_H",
        "#define HUG_TTS_AUDIO_H",
        "#include <Arduino.h>",
        "",
    ]
    for i in range(SENTENCE_COUNT):
        pcm = pcms[i]
        lines.append(f"// line {i} ({len(pcm)} bytes)")
        lines.append(f"static const uint8_t hug_tts_audio_{i}[] = {{")
        for off in range(0, len(pcm), 24):
            chunk = ", ".join(str(b) for b in pcm[off:off + 24])
            lines.append("    " + chunk + ",")
        lines.append("};")
        lines.append("")
    lines.append(f"static const struct {{ const uint8_t* pcm; uint32_t len; }} "
                 f"HUG_TTS_LINES[{SENTENCE_COUNT}] = {{")
    for i in range(SENTENCE_COUNT):
        lines.append(f"    {{ hug_tts_audio_{i}, sizeof(hug_tts_audio_{i}) }},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // HUG_TTS_AUDIO_H")
    OUT_H.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total = sum(len(p) for p in pcms.values())
    print(f"wrote {OUT_H}: {SENTENCE_COUNT} lines, {total} bytes pcm")


def main() -> None:
    ser = serial.Serial(PORT, 115200, timeout=1)
    ser.setDTR(False)
    ser.setRTS(False)   # 触发芯片干净复位(boot 约 3s)

    # 边读边等 boot 完成(丢日志)
    deadline = time.time() + 8.0
    while time.time() < deadline:
        raw = ser.readline()
        if raw and b"boot result=ready" in raw:
            break

    ser.write(b"GO\n")
    ser.flush()
    print("sent GO, capturing...", flush=True)

    pcms: dict[int, bytes] = {}
    current = -1
    expected = 0
    deadline = time.time() + 480
    while time.time() < deadline:
        raw = ser.readline()
        if not raw:
            continue
        line = raw.decode("utf-8", errors="replace").strip()
        m = re.search(r"\[AUDIODUMP\] begin idx=(\d+) bytes=(\d+)", line)
        if m:
            current = int(m.group(1))
            expected = int(m.group(2))
            pcms[current] = bytearray()
            continue
        if line.startswith("hex="):
            if current < 0:
                print("hex before begin?", line[:60], flush=True)
                sys.exit(1)
            # 固件 hex 为小写;板载日志均大写,只收 [0-9a-f] 连续段,天然滤噪
            h = "".join(re.findall(r"[0-9a-f]+", line[4:]))
            if len(h) % 2:
                h = h[:-1]
            pcms[current].extend(bytes.fromhex(h))
            continue
        m = re.search(r"\[AUDIODUMP\] end idx=(\d+)", line)
        if m:
            idx = int(m.group(1))
            got = len(pcms.get(idx, b""))
            print(f"line {idx}: expected {expected} got {got} " + ("OK" if got == expected else "MISMATCH"), flush=True)
            current = -1
            continue
        if "[AUDIODUMP] all done" in line:
            break
        if re.search(r"api action=tts|AUDIODUMP", line):
            print("  dev:", line[:140], flush=True)
    ser.close()

    missing = [i for i in range(SENTENCE_COUNT) if i not in pcms]
    if missing:
        print("missing lines:", missing, flush=True)
        sys.exit(1)
    bad = [i for i, p in pcms.items() if len(p) < 16000]
    if bad:
        print("suspiciously short lines:", bad, flush=True)
        sys.exit(1)
    emit({i: bytes(pcms[i]) for i in range(SENTENCE_COUNT)})


if __name__ == "__main__":
    main()