#!/usr/bin/env python3
"""Generate hug comfort-line bitmask header from the sentence bank.

Reads the sentence bank from src/config.h (single source of truth),
renders each sentence as a 240x40 1bpp mask with a system CJK font,
and writes src/hug_text_bmp.h.

Bit order: MSB-first within each byte, rows top-to-bottom.
A pixel is set when the antialiased glyph coverage exceeds 50%.
"""
import re
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

W = 240
H = 40
THRESHOLD = 96

FONT_CANDIDATES = [
    (r"C:\Windows\Fonts\msyh.ttc", 0),
    (r"C:\Windows\Fonts\msyh.ttf", 0),
    (r"C:\Windows\Fonts\simhei.ttf", 0),
    ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 0),
]
FONT_SIZE = 24

ROOT = Path(__file__).resolve().parents[1]
CONFIG_H = ROOT / "src" / "config.h"
OUT_H = ROOT / "src" / "hug_text_bmp.h"

# 每句的带调拼音(esp_tts_parse_pinyin 输入;1-4 声调,5 轻声,空格分隔)
PINYIN_MAP = {
    "抱抱你，辛苦啦": "bao4 bao4 ni3 xin1 ku3 la5",
    "今天也辛苦了": "jin1 tian1 ye3 xin1 ku3 le5",
    "有我在，不孤单": "you3 wo3 zai4 bu4 gu1 dan1",
    "你已经很棒了": "ni3 yi3 jing1 hen3 bang4 le5",
    "累的时候抱抱我": "lei4 de5 shi2 hou4 bao4 bao4 wo3",
    "我永远都在这里": "wo3 yong3 yuan3 dou1 zai4 zhe4 li3",
    "你值得被温柔以待": "ni3 zhi2 de5 bei4 wen1 rou2 yi3 dai4",
    "休息一下，有我呢": "xiu1 xi1 yi2 xia4 you3 wo3 ne5",
}


def load_sentences() -> list[str]:
    text = CONFIG_H.read_text(encoding="utf-8")
    m = re.search(r"HUG_COMFORT_LINES\s*\[[^\]]*\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        sys.exit("ERROR: HUG_COMFORT_LINES array not found in config.h")
    sentences = re.findall(r'"([^"]*)"', m.group(1))
    if not sentences:
        sys.exit("ERROR: no sentences parsed from config.h")
    return sentences


def load_font():
    for path, index in FONT_CANDIDATES:
        if Path(path).exists():
            return ImageFont.truetype(path, FONT_SIZE, index=index)
    sys.exit("ERROR: no usable CJK font found")


def render_mask(sentence: str, font) -> bytes:
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    tl = d.textlength(sentence, font=font)
    x = max(0, (W - tl) / 2)
    y = max(0, (H - FONT_SIZE) / 2)
    d.text((x, y), sentence, font=font, fill=255)
    px = img.load()
    rows = []
    for yy in range(H):
        byte = 0
        for xx in range(W):
            byte = (byte << 1) | (1 if px[xx, yy] > THRESHOLD else 0)
            if xx % 8 == 7:
                rows.append(byte)
                byte = 0
    assert len(rows) == (W * H) // 8
    return bytes(rows)


def self_check(sentences: list[str], masks: list[bytes]) -> None:
    print(f"T1 self-check: {len(sentences)} sentences parsed")
    for s, m in zip(sentences, masks):
        bits = sum(bin(b).count("1") for b in m)
        # Right-hand overflow check: nothing may set bits beyond the sentence width
        print(f"  set_pixels={bits:5d}  chars={len(s)}  text={s}")
        assert bits > 0, f"empty mask for {s}"
    print("T1 self-check: all masks non-empty")


def emit(sentences: list[str], masks: list[bytes]) -> None:
    bpr = W // 8  # bytes per bitmap row
    lines = []
    lines.append("// Auto-generated by scripts/gen_hug_text.py — do not edit by hand.")
    lines.append("// Comfort-line glyph masks, 240x40, 1bpp, MSB-first, rows top-to-bottom.")
    lines.append("// HUG_TEXT_GBK: same sentences GBK-encoded (esp_tts requires GBK, not UTF-8).")
    lines.append("// Sentences and order follow HUG_COMFORT_LINES in src/config.h.")
    lines.append("#ifndef HUG_TEXT_ARTIFACTS_H")
    lines.append("#define HUG_TEXT_ARTIFACTS_H")
    lines.append(f"#define HUG_TEXT_BMP_W {W}")
    lines.append(f"#define HUG_TEXT_BMP_H {H}")
    lines.append(f"#define HUG_TEXT_BMP_BYTES_PER_LINE {bpr}")
    lines.append("static const uint8_t HUG_TEXT_MASKS[][HUG_TEXT_BMP_BYTES_PER_LINE * HUG_TEXT_BMP_H] = {")
    for s, m in zip(sentences, masks):
        lines.append(f"    // {s}")
        body = ", ".join(str(b) for b in m)
        lines.append("    {" + body + "},")
    lines.append("};")

    # GBK 字节数组(esp_tts_parse_chinese 用),每句 0 结尾,槽位按最长句留足
    gbk_payload: list[bytes] = []
    max_len = 0
    for s in sentences:
        try:
            g = s.encode("gbk")
        except UnicodeEncodeError as e:
            sys.exit(f"ERROR: sentence not GBK-encodable: {s} ({e})")
        gbk_payload.append(g)
        max_len = max(max_len, len(g))
    slot = max_len + 1
    lines.append("")
    lines.append(f"#define HUG_TEXT_GBK_SLOT {slot}")
    lines.append(f"static const uint8_t HUG_TEXT_GBK[HUG_COMFORT_LINES_COUNT][HUG_TEXT_GBK_SLOT] = {{")
    for s, g in zip(sentences, gbk_payload):
        body = ", ".join(str(b) for b in g) + ", 0"
        lines.append(f"    {{{body}}},  // {s}")
    lines.append("};")
    lines.append("")
    lines.append("// Tonal pinyin per sentence, for esp_tts_parse_pinyin")
    lines.append("static const char* const HUG_TEXT_PINYIN[HUG_COMFORT_LINES_COUNT] = {")
    for s in sentences:
        if s not in PINYIN_MAP:
            sys.exit(f"ERROR: missing pinyin for sentence: {s}")
        lines.append(f'    "{PINYIN_MAP[s]}",  // {s}')
    lines.append("};")
    lines.append("")
    lines.append("#endif // HUG_TEXT_ARTIFACTS_H")
    OUT_H.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"T1 wrote {OUT_H} ({len(masks)} masks {bpr * H}B, gbk slot={slot}B)")


def main() -> None:
    sentences = load_sentences()
    font = load_font()
    masks = [render_mask(s, font) for s in sentences]
    self_check(sentences, masks)
    emit(sentences, masks)


if __name__ == "__main__":
    main()