#!/usr/bin/env python3
"""Generate src/hug_tts_audio.h — pre-synthesized audio for the 8 hug lines.

Calls the deployed KuaKua TTS API (POST /api/v1/tts -> wav url -> GET wav),
extracts the PCM payload and emits C arrays the firmware plays from flash.
Run from the firmware directory. Requires network access to the backend.
"""
import json
import re
import ssl
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
API = "https://kuakua-api.cyrusdoyle.me"
OUT_H = ROOT / "src" / "hug_tts_audio.h"

sys.path.insert(0, str(ROOT / "scripts"))
from gen_hug_text import load_sentences  # noqa: E402


def load_env() -> dict[str, str]:
    env = {}
    for line in (ROOT / ".env.local").read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def http_json(url: str, method: str, headers: dict, body: bytes | None):
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE  # 仅限本地一次性生成工具
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    with urllib.request.urlopen(req, context=ctx, timeout=30) as resp:
        return resp.status, resp.read()


def fetch_one(text: str, device_id: str, token: str) -> bytes:
    auth = {"Content-Type": "application/json",
            "X-Device-ID": device_id,
            "Authorization": "Bearer " + token}
    body = json.dumps({"device_id": device_id, "text": text}).encode("utf-8")
    status, raw = http_json(API + "/api/v1/tts", "POST", auth, body)
    if status != 200:
        sys.exit(f"TTS POST failed status={status} body={raw[:200]!r}")
    audio_url = json.loads(raw)["data"]["audio_url"]
    status, wav = http_json(API + audio_url, "GET", auth, None)
    if status != 200 or not wav.startswith(b"RIFF"):
        sys.exit(f"audio GET failed status={status}")
    return wav


def wav_to_pcm(wav: bytes) -> tuple[int, int, bytes]:
    rate = int.from_bytes(wav[24:28], "little")
    channels = int.from_bytes(wav[22:24], "little")
    # find data chunk
    off = 12
    while off + 8 <= len(wav):
        size = int.from_bytes(wav[off + 4: off + 8], "little")
        if wav[off:off + 4] == b"data":
            return rate, channels, wav[off + 8: off + 8 + size]
        off += 8 + size + (size & 1)
    sys.exit("no data chunk in wav")


def emit(entries: list[tuple[str, bytes]]) -> None:
    lines = [
        "// Auto-generated by scripts/gen_hug_audio.py — do not edit by hand.",
        "// Pre-synthesized hug comfort lines (PCM16 mono 16 kHz), indexes match",
        "// HUG_COMFORT_LINES in src/config.h. Played synchronously with the text.",
        "#ifndef HUG_TTS_AUDIO_H",
        "#define HUG_TTS_AUDIO_H",
        "#include <Arduino.h>",
        "",
    ]
    for i, (s, pcm) in enumerate(entries):
        lines.append(f"// {s} ({len(pcm)} bytes)")
        lines.append(f"static const uint8_t hug_tts_audio_{i}[] = {{")
        for off in range(0, len(pcm), 24):
            chunk = ", ".join(str(b) for b in pcm[off:off + 24])
            lines.append("    " + chunk + ",")
        lines.append("};")
        lines.append("")
    lines.append(f"static const struct {{ const uint8_t* pcm; uint32_t len; }} "
                 f"HUG_TTS_LINES[{len(entries)}] = {{")
    for i in range(len(entries)):
        lines.append(f"    {{ hug_tts_audio_{i}, sizeof(hug_tts_audio_{i}) }},")
    lines.append("};")
    lines.append("")
    lines.append("#endif // HUG_TTS_AUDIO_H")
    OUT_H.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total = sum(len(p) for _, p in entries)
    print(f"wrote {OUT_H}: {len(entries)} lines, {total} bytes pcm")


def main() -> None:
    env = load_env()
    device_id = env["K10_BOOTSTRAP_DEVICE_ID"]
    token = env["K10_BOOTSTRAP_TOKEN"]
    sentences = load_sentences()
    entries = []
    for s in sentences:
        wav = fetch_one(s, device_id, token)
        rate, channels, pcm = wav_to_pcm(wav)
        assert rate == 16000 and channels == 1, f"unexpected format {rate} {channels}"
        print(f"  {s}: {len(pcm)} bytes {len(pcm) / 32000:.2f}s")
        entries.append((s, pcm))
    emit(entries)


if __name__ == "__main__":
    main()