ALTER TABLE devices ALTER COLUMN activation_code DROP NOT NULL;
ALTER TABLE devices ALTER COLUMN device_token DROP NOT NULL;
ALTER TABLE devices ALTER COLUMN activated_at DROP NOT NULL;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS device_token_hash VARCHAR(64);
UPDATE devices SET device_token = NULL, device_token_hash = NULL;
ALTER TABLE devices ADD CONSTRAINT uq_devices_serial_number UNIQUE (serial_number);

CREATE TABLE factory_activation_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(64) NOT NULL,
    code_hash VARCHAR(64) NOT NULL UNIQUE,
    kind VARCHAR(16) NOT NULL,
    consumed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE
);

CREATE INDEX idx_factory_activation_codes_device ON factory_activation_codes (device_id);

ALTER TABLE device_images ALTER COLUMN image_url DROP NOT NULL;
ALTER TABLE device_images ADD COLUMN IF NOT EXISTS storage_bucket VARCHAR(64);
ALTER TABLE device_images ADD COLUMN IF NOT EXISTS storage_path VARCHAR(512);
CREATE UNIQUE INDEX uq_device_images_storage_path ON device_images (storage_path);

CREATE TABLE firmware_releases (
    release_id VARCHAR(64) PRIMARY KEY,
    model VARCHAR(64) NOT NULL,
    version VARCHAR(32) NOT NULL,
    storage_bucket VARCHAR(64) NOT NULL,
    storage_path VARCHAR(512) NOT NULL UNIQUE,
    file_size BIGINT NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    manifest TEXT NOT NULL,
    signature TEXT NOT NULL,
    release_notes TEXT,
    channel VARCHAR(16) NOT NULL,
    published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (model, version)
);

CREATE INDEX idx_firmware_releases_model_channel ON firmware_releases (model, channel, published_at);

CREATE TABLE device_heartbeats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id VARCHAR(64) NOT NULL,
    uptime BIGINT,
    memory_usage DOUBLE PRECISION,
    cpu_usage DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE
);

CREATE INDEX idx_device_heartbeats_recorded_at ON device_heartbeats (device_id, recorded_at);
