[env:unihiker]
platform = https://github.com/DFRobot/platform-unihiker.git
board = unihiker_k10
framework = arduino
extra_scripts = pre:scripts/inject_credentials.py
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DModel=None
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    densaugeo/base64@^1.4.0
